{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dify.api.fullname" . }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    {{- if .Values.api.service.labels }}
    {{- toYaml .Values.api.service.labels | nindent 4 }}
    {{- end }}
    component: "api"
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- if .Values.api.service.clusterIP }}
  clusterIP: {{ .Values.api.service.clusterIP }}
  {{- end }}
  ports:
    - name: http-api
      port: {{ .Values.api.service.port }}
      protocol: TCP
      targetPort: api
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    component: "api"
{{- end }}