apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dify.pluginDaemon.fullname" . }}
  labels:
{{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: plugin-daemon
data:
  {{- include "dify.pluginDaemon.config" . | nindent 2 }}
