{{- if and .Values.sandbox.enabled (not (and .Values.externalSecret.enabled .Values.externalSecret.sandbox.enabled)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dify.sandbox.fullname" . }}
  labels:
{{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: sandbox
type: Opaque
data:
  {{- include "dify.sandbox.credentials" . | nindent 2 }}
{{- end }}
