{{- if .Values.ssrfProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dify.ssrfProxy.fullname" . }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    {{- if .Values.ssrfProxy.service.labels }}
    {{- toYaml .Values.ssrfProxy.service.labels | nindent 4 }}
    {{- end }}
    component: "ssrf-proxy"
  {{- with .Values.ssrfProxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- if .Values.ssrfProxy.service.clusterIP }}
  clusterIP: {{ .Values.ssrfProxy.service.clusterIP }}
  {{- end }}
  ports:
    - name: http-squid
      port: {{ .Values.ssrfProxy.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    component: "ssrf-proxy"
{{- end }}