{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dify.web.fullname" . }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    {{- if .Values.web.service.labels }}
    {{- toYaml .Values.web.service.labels | nindent 4 }}
    {{- end }}
    component: "web"
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- if .Values.web.service.clusterIP }}
  clusterIP: {{ .Values.web.service.clusterIP }}
  {{- end }}
  ports:
    - name: http-web
      port: {{ .Values.web.service.port }}
      protocol: TCP
      targetPort: web
  selector:
    {{- include "dify.selectorLabels" . | nindent 4 }}
    component: "web"
{{- end }}