apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dify.web.fullname" . }}
  labels:
{{- include "dify.labels" . | nindent 4 }}
    component: web
data:
  {{- include "dify.web.config" . | nindent 2 }}
